version: '3.9'

services:
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 10s

  migration:
    container_name: migration
    build: ./backend
    command: /bin/sh -c "alembic upgrade head" #  && sleep infinity If we need to do an update to the versioning
    environment:
      - DATABASE_URL=postgresql://postgres:password@database:5432/postgres
    depends_on:
      db:
        condition: service_healthy

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy


volumes:
  db-volume: